insert into advertiser (ad_name) values ('Procyon cancrivorus');
insert into advertiser (ad_name) values ( 'Lycosa godeffroyi');
insert into advertiser (ad_name) values ( 'Anas bahamensis');
insert into advertiser (ad_name) values ( 'Cervus canadensis');
insert into advertiser (ad_name) values ( 'Rhabdomys pumilio');
insert into advertiser (ad_name) values ( 'Coluber constrictor');
insert into advertiser (ad_name) values ( 'Neophoca cinerea');
insert into advertiser (ad_name) values ( 'Ctenophorus ornatus');
insert into advertiser (ad_name) values ( 'Ictonyx striatus');
insert into advertiser (ad_name) values ( 'Ictonyx striatus');
