insert into audience (a_name) values ( 'Idaho Blue-eyed Grass');
insert into audience (a_name) values ( 'Pepper');
insert into audience (a_name) values ( 'Bristly Buttercup');
insert into audience (a_name) values ( 'Blueberry');
insert into audience (a_name) values ( 'Night And Afternoon');
insert into audience (a_name) values ( 'Texas Snoutbean');
insert into audience (a_name) values ( 'Trailing Black Currant');
insert into audience (a_name) values ( 'Cyrtandra');
insert into audience (a_name) values ( 'Lilac Sage');
insert into audience (a_name) values ( 'Black Crowberry');
