insert into container ( c_name, c_type, c_user_id) values ( 'Circle', 'matrices', 1);
insert into container ( c_name, c_type, c_user_id) values ( 'Center', 'Organized', 2);
insert into container ( c_name, c_type, c_user_id) values ( 'Drive', 'Streamlined', 3);
insert into container ( c_name, c_type, c_user_id) values ( 'Plaza', 'multimedia', 4);
insert into container ( c_name, c_type, c_user_id) values ( 'Pass', 'Progressive', 5);
insert into container ( c_name, c_type, c_user_id) values ( 'Court', 'adapter', 6);
insert into container ( c_name, c_type, c_user_id) values ( 'Court', 'artificial intelligence', 7);
insert into container ( c_name, c_type, c_user_id) values ( 'Crossing', 'global', 8);
insert into container ( c_name, c_type, c_user_id) values ( 'Avenue', 'help-desk', 9);
insert into container ( c_name, c_type, c_user_id) values ( 'Street', 'Mandatory', 10);
