insert into container (c_id, c_name, c_type, c_user_id) values (1, 'Circle', 'matrices', 1);
insert into container (c_id, c_name, c_type, c_user_id) values (2, 'Center', 'Organized', 2);
insert into container (c_id, c_name, c_type, c_user_id) values (3, 'Drive', 'Streamlined', 3);
insert into container (c_id, c_name, c_type, c_user_id) values (4, 'Plaza', 'multimedia', 4);
insert into container (c_id, c_name, c_type, c_user_id) values (5, 'Pass', 'Progressive', 5);
insert into container (c_id, c_name, c_type, c_user_id) values (6, 'Court', 'adapter', 6);
insert into container (c_id, c_name, c_type, c_user_id) values (7, 'Court', 'artificial intelligence', 7);
insert into container (c_id, c_name, c_type, c_user_id) values (8, 'Crossing', 'global', 8);
insert into container (c_id, c_name, c_type, c_user_id) values (9, 'Avenue', 'help-desk', 9);
insert into container (c_id, c_name, c_type, c_user_id) values (10, 'Street', 'Mandatory', 10);
