insert into container ( c_name, c_type) values ( 'Circle', 'matrices');
insert into container ( c_name, c_type) values ( 'Center', 'Organized');
insert into container ( c_name, c_type) values ( 'Drive', 'Streamlined');
insert into container ( c_name, c_type) values ( 'Plaza', 'multimedia');
insert into container ( c_name, c_type) values ( 'Pass', 'Progressive');
insert into container ( c_name, c_type) values ( 'Court', 'adapter');
insert into container ( c_name, c_type) values ( 'Court', 'artificial intelligence');
insert into container ( c_name, c_type) values ( 'Crossing', 'global');
insert into container ( c_name, c_type) values ( 'Avenue', 'help-desk');
insert into container ( c_name, c_type) values ( 'Street', 'Mandatory');
