insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (1, 'Cookie Dough - Double', 'APIS MELLIFICA', '2017-11-16', 376, 9, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (2, 'Chicken - Diced, Cooked', 'Rhizopus oryzae', '2017-11-23', 27, 10, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (3, 'Wine - Champagne Brut Veuve', 'Diclofenac Sodium', '2018-06-02', 819, 10, 9);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (4, 'Wine - Hardys Bankside Shiraz', 'good neighbor pharmacy milk of magnesia', '2018-08-23', 261, 6, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (5, 'Crawfish', 'Dr Tichenors', '2017-12-19', 264, 7, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (6, 'Cake - Dulce De Leche', 'Epinephrine', '2017-11-13', 1140, 7, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (7, 'Appetizer - Asian Shrimp Roll', 'Lithium Carbonate', '2018-09-06', 550, 1, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (8, 'Wine - Chateau Bonnet', 'ENLIGHTEN EE EVEN EFFECT SKIN TONE CORRECTOR SPF BROAD SPECTRUM SPF 30', '2018-04-10', 86, 4, 10);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (9, 'Cookies Almond Hazelnut', 'Bisacodyl', '2018-11-04', 995, 7, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (10, 'Calypso - Black Cherry Lemonade', 'ONDANSETRON', '2018-01-30', 546, 10, 9);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (11, 'Soup - Knorr, Veg / Beef', 'pravastatin sodium', '2018-04-16', 517, 9, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (12, 'The Pop Shoppe - Cream Soda', 'Bupropion Hydrochloride', '2018-07-28', 106, 7, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (13, 'Beans - Fine', 'Whole Care', '2018-07-07', 378, 8, 9);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (14, 'Pears - Anjou', 'Equisetum Formica', '2018-05-06', 640, 6, 10);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (15, 'Soup - Cream Of Potato / Leek', 'VESIcare', '2018-06-23', 97, 4, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (16, 'Water - Tonic', 'SEROQUEL', '2018-06-23', 89, 3, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (17, 'Long Island Ice Tea', 'SeptoSan', '2018-08-11', 489, 6, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (18, 'Table Cloth 62x114 Colour', 'Omeprazole', '2018-09-22', 1129, 6, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (19, 'Flour - Teff', 'Clindamycin Hydrochloride', '2018-01-22', 1174, 9, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (20, 'Cocoa Butter', 'SAFEWAY CARE', '2018-01-06', 460, 9, 2);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (21, 'Puree - Kiwi', 'Stool Softener', '2018-08-22', 1078, 3, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (22, 'Wine - Guy Sage Touraine', 'Etodolac', '2017-12-07', 90, 4, 10);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (23, 'Banana', 'Neutrogena', '2018-07-16', 467, 1, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (24, 'Snapple - Iced Tea Peach', 'Quetiapine fumarate', '2018-02-23', 1133, 4, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (25, 'Island Oasis - Strawberry', 'NiteTime Cough', '2018-02-06', 1127, 4, 2);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (26, 'Flower - Potmums', 'Peppermint Mouth Rinse', '2018-05-29', 944, 8, 10);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (27, 'Cafe Royale', 'Pain and Fever', '2018-01-28', 341, 3, 4);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (28, 'Table Cloth 81x81 White', 'Hydroxyzine Hydrochloride', '2017-12-16', 989, 5, 7);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (29, 'Beef - Chuck, Boneless', 'Treatment Set TS331258', '2017-12-07', 321, 8, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (30, 'Pear - Packum', 'potassium chloride', '2018-07-30', 915, 3, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (31, 'Mountain Dew', 'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)', '2017-12-04', 994, 3, 4);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (32, 'Roe - Flying Fish', 'Glyburide', '2018-10-17', 938, 2, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (33, 'Iced Tea - Lemon, 340ml', 'Amlodipine Besylate', '2018-06-14', 995, 6, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (34, 'Contreau', 'Aspirin', '2017-11-14', 961, 5, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (35, 'Aromat Spice / Seasoning', 'Promethazine Hydrochloride', '2017-12-27', 20, 5, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (36, 'Cheese - Provolone', 'A. Dust', '2018-08-03', 756, 7, 9);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (37, 'Soup - French Onion, Dry', 'BPO 6 Foaming', '2018-04-20', 569, 4, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (38, 'Pasta - Rotini, Colour, Dry', 'DIGOXIN', '2018-01-08', 63, 8, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (39, 'Veal - Inside, Choice', 'Anti-Itch', '2018-04-25', 956, 1, 2);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (40, 'Wine - Peller Estates Late', 'Free Radical', '2018-03-17', 1013, 10, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (41, 'Beer - Rickards Red', 'Aralast', '2018-04-15', 1094, 8, 3);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (42, 'Wine - Jafflin Bourgongone', 'MISSHA TIME REVOLUTION WHITE CURE BLANC SUN PROTECTOR', '2018-08-25', 54, 6, 4);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (43, 'Tequila Rose Cream Liquor', 'Molds, Penicillium Mix', '2018-04-22', 434, 6, 5);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (44, 'Capers - Pickled', 'PredniSONE', '2018-03-26', 565, 9, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (45, 'Olives - Kalamata', 'Digoxin', '2017-11-08', 759, 1, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (46, 'Wonton Wrappers', 'Nail Fungus Control', '2018-11-03', 152, 2, 6);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (47, 'Oil - Olive Bertolli', 'Skinovage Nanocell Age Protecting', '2018-10-05', 748, 2, 1);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (48, 'Beans - Black Bean, Preserved', 'AGAVE TEQUILANA', '2018-01-20', 158, 2, 4);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (49, 'Sugar Thermometer', 'AlphaNine', '2018-05-12', 419, 2, 8);
insert into drink (d_id,  d_name, d_brand, d_expiredate, d_calories, d_quantity, d_container_id) values (50, 'Skirt - 29 Foot', 'SHISEIDO WHITE LUCENT BRIGHTENING PROTECTIVE W', '2018-04-28', 29, 10, 7);
