insert into food_tag(ft_food_id, ft_tag_id) values ( 1, 1);
insert into food_tag(ft_food_id, ft_tag_id) values ( 2, 2);
insert into food_tag(ft_food_id, ft_tag_id) values ( 3, 3);
insert into food_tag(ft_food_id, ft_tag_id) values ( 4, 4);
insert into food_tag(ft_food_id, ft_tag_id) values ( 5, 5);
insert into food_tag(ft_food_id, ft_tag_id) values (6, 6);
insert into food_tag(ft_food_id, ft_tag_id) values ( 7, 7);
insert into food_tag(ft_food_id, ft_tag_id) values ( 8, 8);
insert into food_tag(ft_food_id, ft_tag_id) values ( 9, 9);
insert into food_tag(ft_food_id, ft_tag_id) values ( 10, 10);