insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Crab - Dungeness, Whole, live', 'Wart Cleanse', '2017-11-16', 722, 5, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Bread - Olive', 'Cepastat', '2018-09-18', 415, 6, 9);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Snapple - Mango Maddness', 'Calcium Acetate', '2018-02-28', 858, 2, 7);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Tamarillo', 'Enalapril Maleate and Hydrochlorothiazide', '2017-11-26', 273, 2, 8);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Veal - Sweetbread', 'Morphine sulfate', '2017-12-16', 132, 7, 7);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Beef - Rib Eye Aaa', 'Crest Complete Multi-Benefit', '2017-12-10', 923, 1, 3);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Passion Fruit', 'Colgate Optic White Platinum', '2018-01-10', 703, 8, 7);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Pasta - Rotini, Dry', 'Namenda', '2018-02-06', 870, 6, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Eel Fresh', 'CURE ATHLETES FOOT', '2018-06-02', 578, 9, 2);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Olives - Green, Pitted', 'Foot Care Clotrimazole', '2018-03-09', 295, 5, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Cocoa Powder - Natural', 'Effervescent Potassium Chloride', '2018-01-01', 337, 5, 2);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Chevere Logs', 'Galantamine', '2018-07-12', 776, 10, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Pepper - Chilli Seeds Mild', 'PROVENCE TWO WAY PACT', '2017-12-29', 928, 9, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Apple - Northern Spy', 'Telmisartan', '2018-02-21', 1040, 7, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Clams - Canned', 'Ceftriaxone Sodium', '2017-11-11', 84, 5, 1);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Onions - Vidalia', 'Therabenzaprine-60', '2018-04-16', 1096, 5, 3);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Bouillion - Fish', 'Desvenlafaxine', '2018-05-03', 87, 3, 1);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Trout - Rainbow, Frozen', 'Witch Hazel', '2018-06-15', 628, 4, 7);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Pate Pans Yellow', 'CVS Pharmacy Glycerin', '2018-01-15', 1040, 9, 2);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Toamtoes 6x7 Select', 'Diphenhydramine Hydrochloride', '2018-10-21', 879, 4, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Irish Cream - Butterscotch', 'ESZOPICLONE', '2018-06-29', 539, 3, 3);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Clams - Canned', 'MOXATAG', '2018-06-01', 957, 7, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Pernod', 'TERCONAZOLE', '2018-08-01', 588, 7, 8);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Potatoes - Idaho 100 Count', 'ATORVASTATIN CALCIUM', '2018-06-22', 1133, 9, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Goldschalger', 'Homeopathic Scar', '2017-12-24', 871, 3, 9);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Ecolab - Hobart Washarm End Cap', 'SHISEIDO WHITE LUCENT BRIGHTENING SPOT-CONTROL FOUNDATION (REFILL)', '2018-07-05', 1021, 1, 7);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Broom - Push', 'Sooryehan Pure-Whitening', '2018-02-09', 490, 6, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Jello - Assorted', 'Ketorolac Tromethamine', '2017-11-11', 900, 8, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Rabbit - Legs', 'tussin cough', '2018-04-29', 914, 5, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Tomato - Peeled Italian Canned', 'Cetirizine Hydrochloride', '2018-09-13', 967, 8, 1);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Cheese - Shred Cheddar / Mozza', 'Sensodyne', '2018-10-26', 726, 5, 10);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Silicone Parch. 16.3x24.3', 'SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)', '2018-09-28', 305, 3, 8);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Madeira', 'Rifadin', '2018-08-20', 742, 2, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Kumquat', 'ULTRASOL', '2018-05-05', 513, 8, 9);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Cinnamon - Ground', 'Betamethasone Dipropionate', '2018-10-16', 977, 10, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Wine - White, Antinore Orvieto', 'Synthroid', '2018-02-06', 107, 2, 2);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Ecolab Digiclean Mild Fm', 'topcare lice treatment', '2018-11-05', 367, 4, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Puree - Guava', 'Oxcarbazepine', '2018-02-18', 929, 6, 5);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Chocolate Bar - Smarties', 'Rimmel London', '2018-06-23', 142, 4, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Nantucket - 518ml', 'antacid', '2018-03-28', 514, 9, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Gloves - Goldtouch Disposable', 'Carvedilol', '2018-05-20', 124, 5, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Lotus Leaves', 'RHINOCORT AQUA', '2018-05-01', 368, 8, 8);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Thermometer Digital', 'Necon 777', '2018-10-21', 608, 2, 10);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Compound - Orange', 'Sunmark infants gas relief drops', '2017-12-18', 790, 5, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Wine - Barbera Alba Doc 2001', 'EndaCof DM', '2018-05-09', 935, 1, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Calaloo', 'ShopRite Tioconazole 1', '2017-12-26', 245, 8, 4);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Ham - Virginia', 'Avelox', '2018-08-10', 979, 3, 1);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Lotus Leaves', 'Olay Fresh Effects Clear Skin', '2018-08-05', 1047, 7, 6);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Bok Choy - Baby', 'Back and Neck Rescue', '2018-08-13', 935, 10, 8);
insert into item ( f_name, f_brand, f_expiredate, f_calories, f_quantity, f_container_id) values ( 'Cheese - Swiss Sliced', 'HAND AND NATURE ANTI WRINKLE HAND', '2018-01-14', 713, 4, 8);
