insert into tag (t_name) values ( 'Natural Language Processing');
insert into tag (t_name) values ( 'Test Automation');
insert into tag (t_name) values ( 'Supervisory Skills');
insert into tag (t_name) values ( 'Kaseya');
insert into tag (t_name) values ( 'AHLTA');
insert into tag (t_name) values ( 'BPD');
insert into tag (t_name) values ( 'OSHA 30-Hour');
insert into tag (t_name) values ( 'FPC 1');
insert into tag (t_name) values ( 'QRC');
insert into tag (t_name) values ( 'Agarose Gel Electrophoresis');
